import { sqliteTable, text, integer, real } from "drizzle-orm/sqlite-core";
import { sql } from "drizzle-orm";
import { createInsertSchema } from "drizzle-zod";
import { z } from "zod/v4";

export const knowledgeTable = sqliteTable("knowledge", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  createdAt: text("created_at").default(sql`(datetime('now'))`).notNull(),
  lastUsed: text("last_used"),
  useCount: integer("use_count").default(1).notNull(),
  problemType: text("problem_type").notNull(),
  language: text("language").notNull(),
  framework: text("framework"),
  patternTags: text("pattern_tags"),
  fileType: text("file_type"),
  question: text("question").notNull(),
  contextHash: text("context_hash"),
  codeSnippet: text("code_snippet"),
  answer: text("answer").notNull(),
  actionItems: text("action_items"),
  confidence: text("confidence").notNull(),
  provider: text("provider").notNull(),
  domain: text("domain"),
  // JSON-stringified 384-dim vector generated by all-MiniLM-L6-v2.
  embedding: text("embedding"),
  wasUseful: integer("was_useful").default(1).notNull(),
  producedBugs: integer("produced_bugs").default(0).notNull(),
  qualityScore: real("quality_score").default(0.5).notNull(),
});

export const insertKnowledgeSchema = createInsertSchema(knowledgeTable).omit({ id: true, createdAt: true });
export type InsertKnowledge = z.infer<typeof insertKnowledgeSchema>;
export type Knowledge = typeof knowledgeTable.$inferSelect;
