import { sqliteTable, text, integer, real } from "drizzle-orm/sqlite-core";
import { sql } from "drizzle-orm";

export const metricSnapshotsTable = sqliteTable("metric_snapshots", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  timestamp: text("timestamp").notNull().default(sql`(datetime('now'))`),
  healthScore: real("health_score").default(0).notNull(),
  coverageOverall: real("coverage_overall").default(0).notNull(),
  predictionAccuracyScore: real("prediction_accuracy_score").default(0).notNull(),
  falseNegativeRate: real("false_negative_rate").default(0).notNull(),
  confidenceCalibrationIndex: real("confidence_calibration_index").default(0).notNull(),
  recommendationFixConversion: real("recommendation_fix_conversion").default(0).notNull(),
  testGenerationEffectiveness: real("test_generation_effectiveness").default(0).notNull(),
  kpiSampleSize: integer("kpi_sample_size").default(0).notNull(),
  reinforcementAttempts: integer("reinforcement_attempts").default(0).notNull(),
  reinforcementApplied: integer("reinforcement_applied").default(0).notNull(),
  reinforcementBoosts: integer("reinforcement_boosts").default(0).notNull(),
  reinforcementDecays: integer("reinforcement_decays").default(0).notNull(),
  reinforcementNet: integer("reinforcement_net").default(0).notNull(),
  reinforcementCoverage: real("reinforcement_coverage").default(0).notNull(),
  agingPersonalUpdates: integer("aging_personal_updates").default(0).notNull(),
  agingKnowledgeUpdates: integer("aging_knowledge_updates").default(0).notNull(),
  activeAgents: integer("active_agents").default(0).notNull(),
  pausedAgents: integer("paused_agents").default(0).notNull(),
  totalBugs: integer("total_bugs").default(0).notNull(),
  kbHitRate: real("kb_hit_rate").default(0).notNull(),
  tasksCompleted: integer("tasks_completed").default(0).notNull(),
  escalationsToday: integer("escalations_today").default(0).notNull(),
  cpuUsage: real("cpu_usage").default(0).notNull(),
  memoryMb: real("memory_mb").default(0).notNull(),
});
